# https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
language: python

sudo: false

cache:
  pip: true

python:
  - 2.7

services:
  - docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

cache:
  bundler: true
  directories:
    - $HOME/docker

install:
  - pip install -U tox-travis codecov

script:
  - bash test-container.sh

after_success:
  - codecov --disable search

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: <REPLACE>
  password: <REPLACE THIS AND RUN `travis encrypt --add deploy.password`>
  on:
    tags: true
    repo: zhouyangyu/cache_dockerimage_in_travis
    python: 2.7
    branch: master
